@startuml
title "CFM Sequence Diagram"

box "ADC/LSM"
participant cm as "CenterFileManager"
participant dfs as "DFS"
end box

box "VOD"
participant cw1 as "CenterFileWorker-1"
participant dfs1 as "DFS-1"
participant va1 as "vodSubAgent-1"
end box

box "VOD(Source)"
participant cw2 as "CenterFileWorker-2"
participant dfs2 as "DFS-2"
participant va2 as "vodSubAgent-2"
end box

loop schedule file 발견할 때까지
cw1->cw1: scheule file polling
end

loop schedule file 발견할 때까지
cw2->cw2: scheule file polling
end

cm->cm: file meta 생성
cm->dfs1: file list 조회
cm->dfs2: file list 조회
cm->va2: vod service traffic 조회
cm->cm: 배포 schedule 생성
cm->cm: 삭제 schedule 생성
cm->dfs1: schedule 전송
cw1->cw1: schdule file 파싱
cw1->cw1: file 삭제
cw1->dfs2: file 다운로드 요청

loop 모든 schedule이 종료될 떄까지
cw1->dfs: file 다운로드 중 heartbeat file 전송
cm->cm: heartbeat file 확인
opt heartbeat file 이 없을 경우
    cm->cm: heartbeat file 이 없는 worker 의 schedule 종료 처리
end
cw1->cm: file 다운로드 완료 후 response file 전송
cm->cm: response file 확인
opt response file 이 있을 경우
    cm->cm: response file 이 있는 worker 의 schedule 종료 처리
end
cm->cm: 10초 sleep
end
@enduml